apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  createdAt: 2023-04-18T00:00:00Z
  name: boutique-cart-pod-delete
  version: 0.1.0
  annotations:
    categories: boutique-cart
    chartDescription: Injects chaos on boutique-cart application by deleting a pod replica and checking the availability of the application.
spec:
  displayName: Boutique Cart Pod Delete
  categoryDescription: >
    This chart installs a chaos experiment to delete a pod of the boutique-cart microservice application,
    causing disruption and testing resilience of the application.
  experiments:
    - name: pod-delete
      description: "Deletes pod replicas of the boutique-cart deployment"
  keywords:
    - Kubernetes
    - Boutique-cart
    - Pod
    - Delete
  platforms:
    - GKE
    - Minikube
    - Packet(Kubeadm)
    - EKS
    - AKS
  maintainers:
    - name: Raj Babu
      email: rajbabu.das@harness.io
  provider:
    name: Harness
  links:
    - name: Kubernetes Slack
      url: https://slack.kubernetes.io/
    - name: Documentation
      url: https://docs.litmuschaos.io/docs/chaoshub/#generic-chaos
  icon:
    - url: 
      mediatype: ""
