---
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: restrict-host-ns-usage
  annotations:
    policies.kyverno.io/category: Pod Security Standards
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Host namespaces (Process ID namespace, Inter-Process Communication namespace, and
      network namespace) allow access to shared information and can be used to elevate
      privileges. Pods should  allowed access to host namespaces.      
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: restrict-host-ns-usage
      match:
        resources:
          kinds:
            - Pod
          selector:
            matchLabels:
              # restrict the experiment to use host ns
              app.kubernetes.io/restrict-host-ns-usage: "true"
      validate:
        message: >-
          The spec.hostNetwork, spec.hostIPC, and spec.hostPID should be false.
        pattern:
          spec:
            =(hostPID): "false"
            =(hostIPC): "false"
            =(hostNetwork): "false"
            